export const mockMovies = {
  trending: [
    {
      title: "Dark Crystal Chronicles",
      year: "2024",
      rating: "TV-14",
      genre: "Fantasy",
      duration: "52m",
    },
    {
      title: "Mystic Realms",
      year: "2023",
      rating: "TV-MA",
      genre: "Adventure",
      duration: "47m",
    },
    {
      title: "Shadow Academy",
      year: "2022",
      rating: "TV-14",
      genre: "Drama",
      duration: "43m",
    },
    {
      title: "Storm Runners",
      year: "2024",
      rating: "TV-MA",
      genre: "Action",
      duration: "38m",
    },
    {
      title: "Royal Intrigue",
      year: "2023",
      rating: "TV-MA",
      genre: "Drama",
      duration: "55m",
    },
    {
      title: "Digital Hearts",
      year: "2024",
      rating: "TV-MA",
      genre: "Romance",
      duration: "42m",
    },
    {
      title: "Underground Wars",
      year: "2021",
      rating: "TV-MA",
      genre: "Thriller",
      duration: "49m",
    },
    {
      title: "Mind Games",
      year: "2021",
      rating: "TV-MA",
      genre: "Sci-Fi",
      duration: "44m",
    },
  ],

  popular: [
    {
      title: "Chemistry Lab",
      year: "2013",
      rating: "TV-MA",
      genre: "Drama",
      duration: "47m",
    },
    {
      title: "Legal Defense",
      year: "2022",
      rating: "TV-MA",
      genre: "Legal",
      duration: "52m",
    },
    {
      title: "Time Paradox",
      year: "2020",
      rating: "TV-MA",
      genre: "Sci-Fi",
      duration: "45m",
    },
    {
      title: "City Undercover",
      year: "2017",
      rating: "TV-MA",
      genre: "Crime",
      duration: "48m",
    },
    {
      title: "Power Plays",
      year: "2018",
      rating: "TV-MA",
      genre: "Political",
      duration: "56m",
    },
    {
      title: "Prison Chronicles",
      year: "2019",
      rating: "TV-MA",
      genre: "Drama",
      duration: "42m",
    },
    {
      title: "Future Shock",
      year: "2019",
      rating: "TV-MA",
      genre: "Anthology",
      duration: "51m",
    },
    {
      title: "Detective Stories",
      year: "2019",
      rating: "TV-MA",
      genre: "Crime",
      duration: "46m",
    },
  ],

  streamflixOriginals: [
    {
      title: "Chess Master's Journey",
      year: "2020",
      rating: "TV-MA",
      genre: "Drama",
      duration: "58m",
    },
    {
      title: "Time Loop Mystery",
      year: "2022",
      rating: "TV-MA",
      genre: "Sci-Fi",
      duration: "43m",
    },
    {
      title: "Hero Academy",
      year: "2024",
      rating: "TV-14",
      genre: "Superhero",
      duration: "39m",
    },
    {
      title: "Angel Detective",
      year: "2021",
      rating: "TV-14",
      genre: "Fantasy",
      duration: "44m",
    },
    {
      title: "Haunted Manor",
      year: "2018",
      rating: "TV-MA",
      genre: "Horror",
      duration: "32m",
    },
    {
      title: "Teen Diaries",
      year: "2020",
      rating: "TV-MA",
      genre: "Drama",
      duration: "28m",
    },
    {
      title: "Elite Society",
      year: "2024",
      rating: "TV-MA",
      genre: "Drama",
      duration: "47m",
    },
    {
      title: "Growing Up Digital",
      year: "2023",
      rating: "TV-MA",
      genre: "Comedy",
      duration: "25m",
    },
  ],
};
